entsog_new.get_flows <- function(date_from='2022-01-01', use_cache=T){

  # Read files generated by Python scraper
  flows <- read_csv("../../fossil_shipment_tracker/entsog_flows_False_False_False_True.csv") %>%
    filter(date>=date_from)

  flows <- flows %>%
    mutate(value=value/1000) %>% #value is now in MWh / day
    select(-c(index))


  # Distribute to source country using our iterative method
  flows_sourced <- pbapply::pblapply(split(flows, flows$date), function(df){process_iterative(df) %>% mutate(date=unique(df$date))}) %>%
    do.call(bind_rows,.)

  flows_sourced  <- bind_rows(
    flows_sourced,
    flows %>%
      filter(from_country==to_country)
  )

  sum(flows_sourced$value[flows_sourced$from_country=='Russia'], na.rm=T) / 1e9
  sum(flows$value[flows$from_country=='Russia']) / 1e9

  flows_sourced <- flows_sourced %>%
    rename(value_mwh=value) %>%
    mutate(value_tonne=value_mwh/gcv_MWh_per_m3*kg_per_m3/1000) %>%
    mutate(value_m3=value_mwh/gcv_MWh_per_m3) %>%
    mutate(commodity='natural_gas')

  sum(flows_sourced$value[flows_sourced$from_country==flows_sourced$to_country]) == 0

  # Add production
  flows_sourced <- bind_rows(
    flows_sourced,
    flows %>%
      filter(from_country==to_country) %>%
      rename(value_mwh=value) %>%
      mutate(value_tonne=value_mwh/gcv_MWh_per_m3*kg_per_m3/1000) %>%
      mutate(value_m3=value_mwh/gcv_MWh_per_m3) %>%
      mutate(commodity='natural_gas')) %>%
    select(from_country, to_country, date, value_m3)


  # Plotting diagnosis
  # all_res_agg <- bind_rows(
  #   flows_sourced,
  #   flows_sourced %>%
  #     rename(from_country=to_country,
  #            to_country=from_country) %>%
  #     mutate(value=-value)) %>%
  #   group_by(from_country, to_country, method) %>%
  #   summarise(value=sum(value, na.rm=T))
  #
  # ggplot(all_res_agg,
  #        aes(from_country, to_country, fill = value, label = ifelse(value!=0, sprintf("%.1f", value/1e9), ""))) +
  #   geom_tile() +
  #   geom_text(col = "black") +
  #   theme_minimal() +
  #   scale_fill_distiller(palette="Spectral") +
  #   # scale_color_gradient2(low = "white", mid = "yellow", high = "red") +
  #   facet_wrap(~method, ncol=1)

  return(flows_sourced)

}
