entsog_new.get_flows <- function(date_from='2021-11-01', date_to=NULL, use_cache=T){

  # Read files generated by Python scraper

  if(is.null(date_to)){
    date_to <-as.character(lubridate::today() + lubridate::days(1))
  }

  flows <- read_csv(sprintf("https://api.russiafossiltracker.com/v0/entsogflow?type=crossborder,production&format=csv&date_from=%s&date_to=%s", date_from, date_to))

  flows_formatted <- flows %>%
    select(from_country=commodity_origin_iso2,
           to_country=commodity_destination_iso2,
           date,
           value=value_m3)

  # Distribute to source country using our iterative method
  flows_sourced <- pbapply::pblapply(split(flows_formatted, flows_formatted$date),
                                     function(df){process_iterative(df) %>%mutate(date=unique(df$date))}) %>%
    do.call(bind_rows,.)

  sum(flows_sourced$value[flows_sourced$from_country=='RU'], na.rm=T) / 1e9
  sum(flows_formatted$value[flows_formatted$from_country=='RU']) / 1e9
  sum(flows_sourced$value[flows_sourced$from_country==flows_sourced$to_country],na.rm=T)/1e9 == 0

  # Add production
  flows_sourced  <- bind_rows(
    flows_sourced %>%
      filter(from_country!=to_country),
    flows_formatted %>%
      filter(from_country==to_country)
  )


  flows_sourced <- flows_sourced %>%
    mutate(value=round(value, 2)) %>% # Some values are ~-1e-15
    rename(value_m3=value) %>%
    mutate(value_tonne=value_m3*kg_per_m3/1000) %>%
    mutate(value_mwh=value_m3*gcv_kWh_per_m3/1000) %>%
    mutate(commodity='natural_gas') %>%
    rename(departure_iso2=from_country,
           destination_iso2=to_country)


  # Plotting diagnosis
  # all_res_agg <- bind_rows(
  #   flows_sourced,
  #   flows_sourced %>%
  #     rename(from_country=to_country,
  #            to_country=from_country) %>%
  #     mutate(value=-value)) %>%
  #   group_by(from_country, to_country, method) %>%
  #   summarise(value=sum(value, na.rm=T))
  #
  # ggplot(all_res_agg,
  #        aes(from_country, to_country, fill = value, label = ifelse(value!=0, sprintf("%.1f", value/1e9), ""))) +
  #   geom_tile() +
  #   geom_text(col = "black") +
  #   theme_minimal() +
  #   scale_fill_distiller(palette="Spectral") +
  #   # scale_color_gradient2(low = "white", mid = "yellow", high = "red") +
  #   facet_wrap(~method, ncol=1)

  return(flows_sourced)

}
