# Deploy production
name: Force deploy (production)

on: workflow_dispatch

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Authenticate with Google Cloud
        id: "auth"
        uses: "google-github-actions/auth@v1"
        with:
          credentials_json: "${{ secrets.GCP_SA_KEY }}"
      - name: Docker login
        run: gcloud auth configure-docker  europe-west1-docker.pkg.dev --quiet

      - name: Set up buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and deploy latest docker image
        uses: docker/build-push-action@v5
        id: build-and-deploy-image
        with:
          context: .
          file: Dockerfile
          tags: europe-west1-docker.pkg.dev/${{ secrets.PROJECT_ID }}/tracker/engine-r:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          push: true

  release:
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}
      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
      - name: Tag built image as latest
        run: |
          gcloud container images add-tag \
          europe-west1-docker.pkg.dev/${{ secrets.PROJECT_ID }}/tracker/engine-r:${{ github.sha }} \
          europe-west1-docker.pkg.dev/${{ secrets.PROJECT_ID }}/tracker/engine-r:latest
      - name: Deploy latest job specs
        id: deploy-job-spec
        run: |
          gcloud run jobs replace infra/jobs/engine-r.yaml
